apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Test-one
  description: platform for improved Developer Experience.
  annotations:
    bitbucket.atlassian.com/repository: BS/telstra-backstage
    goharbor.io/repository-slug: tools-backstage/backstage-fe
    qameta.io/allure-project: allure-lambda-test
    telstra.alfabetcloud.com/ability-app-id: app-3328
    sonarqube.org/project-key: 'com.telstra:quarterback'
  tags:
    - typescript
    - nodejs
    - reactjs
    - platform
    - dx
    - inner-source
spec:
  type: website
  owner: Arjun
  lifecycle: production
